name: Auto Assign Issues/PRs

on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  assign:
    runs-on: ubuntu-latest
    
    steps:
    - name: Auto Assign Issues/PRs
      uses: wow-actions/auto-assign@v3.0.2
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Replace with your secret token
        addReviewers: true
        addAssignees: true
        reviewers: JRigles
        assignees: JRiggles
        numberOfReviewers: 0
        numberOfAssignees: 0
        skipKeywords: wip, draft
        skipDraft: true
        # includeLabels:
        # excludeLabels:
